### PR TITLE
fix date function format

### PR DESCRIPTION
**Pull request by dibmartins**
I remove the double quotes of date("'Y-m-d H:i:s'");

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.0.x` branch?

**Comment by dibmartins** [comment]
done.

**Comment by sergeyklay** [comment]
This branch has conflicts that must be resolved. This happened because you sent the PR from master to the `3.0.x`. 
pr-conflict

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch. Thanks

**Pull request closed without merging**
