### PR TITLE
#425 Remove requirement ext-phalcon

### PR DESCRIPTION
**Pull request by ryomo**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Why?

**Comment by sergeyklay** [comment]
We don't add changes directly to `master`, could you please submit this to the branch `2.0.x`?

**Comment by ryomo** [comment]
>Why?
Because someone like me install ext-phalcon not on the local machine but on virtual machines.
IDE is installed on the local machine.
(issue #425 )
Sorry for my bad English.

>We don't add changes directly to master, could you please submit this to the branch 2.0.x?
I made new PR( #428 ).

**Comment by virgofx** [comment]
The current master still has ext-phalcon as a requirement. Devtools should not require this as it does prohibit installations for composer where IDEs and development environments which to include this as a development dependency.

**Comment by sergeyklay** [comment]
use `php composer.phar install --ignore-platform-reqs`

**Pull request closed without merging**
