### PR TITLE
Add feature to reverse a migration

### PR DESCRIPTION
**Pull request by frohlfing**
As until now the up function is called if you migrate to a higher version. For the reverse migration the down function is called instead. In addition the morph function will be called in both cases (if existing).

### CODE REVIEW

**Comment by sergeyklay** [comment]
@gently69 The PR needs to be rebased

**Comment by sergeyklay** [comment]
@rohfra The PR needs to be rebased

**Comment by Green-Cat** [comment]
:+1: for rollbacks

**Comment by TrogWarZ** [comment]
Rollback is good!

@frohlfing , why you remove checks for files existence and versions? Maybe, just check return value from up() method (or throw exception) and rollback by this flag?

**Comment by sergeyklay** [comment]
@frohlfing ping

**Comment by frohlfing** [comment]
Pong :-)

I'm very busy at the moment. I will be make a rebase next month.

**Comment by sergeyklay** [comment]
@frohlfing

**Pull request closed without merging**
