### PR TITLE
Align stubs with real zephir methods requirements

### PR DESCRIPTION
**Pull request by SachaMorard**

### CODE REVIEW

**Comment by ovr** [comment]
Stubs was generated automatically by `zephir stubs`
Why are you committing it?

**Comment by SachaMorard** [comment]
Hi
Because my ide prints error when php not, and php launch exception when my ide doesn't print any errors.
This appears especially when I have to overload Phalcon classes.
Is there any problem with stubs generation ?

**Comment by sergeyklay** [comment]
At least it doesn't breaks nothing :)

**Comment by sergeyklay** [comment]
@SachaMorard Thanks.

**Comment by sergeyklay** [comment]
@SachaMorard Create PR to 2.0.x please

**Comment by SachaMorard** [comment]
Thanks ;)

**Pull request merged**
