### PR TITLE
Prevents double firing methods down() on downgrade.

### PR DESCRIPTION
**Pull request by reczu**

### CODE REVIEW

**Comment by sergeyklay** [comment]
This constant introduced to solve #520 issue
See: bdd0266f19d42221882124970c90f179ad40fab6

**Comment by reczu** [comment]
I have migration 1.0.1 with file test.php with up and down methods no morph

```php
...

   /**
     * Run the migrations
     *
     * @return void
     */
    public function up()
    {
        self::$_connection->addColumn('test', null, new Column('new_col', array('type' => Column::TYPE_VARCHAR, 'size' => 50,)));
    }

    /**
     * Reverse the migrations
     *
     * @return void
     */
    public function down()
    {
        self::$_connection->dropColumn('test', null, 'new_col');
    }
...
```

So if i try to rollback to version 1.0.0 i get following error:

```
Phalcon DevTools (2.0.10)

1456237484.2396: ALTER TABLE "test" DROP COLUMN "new_col"  => 1456237484.2424 (0.0027918815612793)
                                                    
  Success: Version 1.0.1 was successfully migrated  
                                                    
1456237484.243: ALTER TABLE "test" DROP COLUMN "new_col"ERROR: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "new_col" of relation "test" does not exist
```

As you can see it fires method down twice and breaks migration.

**Comment by Daredzik** [comment]
+1

**Comment by sergeyklay** [comment]
I'll try to deal with this in the near future. Ping me if I forget

**Comment by mokeev1995** [comment]
@sergeyklay ping

**Comment by sergeyklay** [comment]
@sergeysviridenko Could you please take a look

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Pull request closed without merging**
