### PR TITLE
#1282 - PHP upgrade from 5 to 7.2

### PR DESCRIPTION
**Pull request by Jeckerson**
Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [Contributing Guidelines][:contrib:]
- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR

Small description of change:

Thanks

[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by CameronHall** [comment]
There is a bug in a specific version of 7.3, I think it's 7.3.3 but I might be wrong. Can we please make sure the version constraint says that version of PHP is incompatible? 

` 7.2 - 7.3.2 || >7.3.3`

**Comment by Jeckerson** [comment]
@CameronHall It also can be bug in devtools code. Need detailed checks. Will think about it.

**Comment by dschissler** [comment]
@CameronHall That is fine to polish these things for release but why would this be blocked now while Phalcon is still in alpha?  I'm 100% only working with Phalcon 4 now and so I can't even run the Dev Tools at all, wrong minor versions or not.  I did TONS of Dev Tools work for the book, in fact I completely redesigned the old absolutely terrible `modules` template (it was so miserably worthless before that).  My point is that I want to work with the Dev Tools now and to push actual code fixes but I CAN'T because you guys are blocking the entire project for what seems like from a distance a straight up autistic neurosis.  Phalcon can be so damn SLLLLLLLLOOOOOOOOOOWWWwwwww.  There is a price for this.  I love Phalcon but sometimes you put my eyes at risk of rolling straight out of my head.

I suggest, "get it in there, refine it later" - David Schissler 2019.

**Comment by CameronHall** [comment]
I'm sorry you feel that way. Would you mind elaborating on how we're blocking the dev-tools project? From what I can tell, there is _nothing_ stopping you (nor anyone else) from creating a pull request to address any issues you encounter.

**Comment by dschissler** [comment]
In less words this ` "ext-phalcon": "~4.0",`.  Now there were only two lines of change in this commit but I'm happy to point it out for you.

**Comment by CameronHall** [comment]
I don't see a problem with `"ext-phalcon": "~4.0"`. This is going to the 4.0.x branch and `~4.0` will cover `>=4.0.0.0-dev <5.0.0.0-dev`.

If you have a question or concern about changes to a pull request, feel free to use the "Code Review" feature and leave a comment against the line in question. [Here's a tutorial](https://www.youtube.com/watch?v=HW0RPaJqm4g)

It's far more than constructive and productive than being ambiguous and insulting.

**Comment by dschissler** [comment]
Its the fact that you are not merging this code which is the problem.  I'm done here.  This is ridiculous.

**Comment by CameronHall** [comment]
@dschissler that's because it's still a draft and @Jeckerson is still working on it. Had you been more explicit in the first place, then I would have understood your problem.  If you want this fixed immediately then create you may own pull request and I'll approve it as soon as I see it. I'm unsure if you use Discord, but if you do feel free to ping us on [there](http://phalcon.link/discord) if you need.

**Comment by dschissler** [comment]
I appreciate that but I'm moving on.

**Comment by Jeckerson** [comment]
wtf, @dschissler chill man. I just started to prepare things to 4.x. Main idea for this PR is just make running version of dev-tools for Phalcon 4. If you have some work done for 4 dev-tools, so decompose it in some small tasks, create issues for each and create PR's, to make sure all will work.

Peace yo!

**Comment by dschissler** [comment]
> so decompose it in some small tasks,

@Jeckerson You are prescribing a different approach than what you yourself are doing.  I'd have been super happy if either of you had been following your just given advice ("decompose ... small task") by just merging the blocker for 99.99% of everyone to have in their tree.  Then everyone can be working off a tree that keeps working getting along with each commit.  You're leveraging the community very poorly that is an institutional problem with Phalcon.  I wish that I'd just never seen your PR.

**Comment by Jeckerson** [comment]
I described that I'll try to make minimum possible to just run dev-tools with phalcon 4.0. And first thing that I do - is to remove old PHP version dependency. If I'll notice that current branch is growing, then I'll break into smaller tasks that will enter firstly into branch 4.x.

**Comment by dschissler** [comment]
If things had gone a different way then I would have done that work already.  Good luck.

**Comment by niden** [comment]
First and last time I type this. @dschissler @Jeckerson @CameronHall 

Contributing to Phalcon and and its repositories is everyone's choice. You contribute as much or as little as you want. 

Being courteous to others **is a requirement** and not negotiable. One can make one's point without insulting others.

If I see outbursts like this in the future, the ban hammer will drop.

_Treat others the way you want to be treated_

**Comment by denysaw** [comment]
Guys, for Phalcon 4.0 just:
```"require": {
	"ext-phalcon": "4.0.0-alpha.3 as 3.3.2"
}```
in your main composer.json ;)

**Pull request merged**
