### PR TITLE
Added @autogenerated to model doc 

### PR DESCRIPTION
**Pull request by 7thcubic**

### CODE REVIEW

**Comment by sergeyklay** [comment]
It is really needed `@autogenerated` ?

**Comment by 7thcubic** [comment]
someone opened an issue for it. helleva i know? lol

**Comment by sergeyklay** [comment]
The PR needs to be rebased, and fix indents please

**Comment by 7thcubic** [comment]
Its done. rebased and forced update on the same branch.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
