### PR TITLE
Adapt the php-dev-tools to work with oldest version of PHP < 5.4

### PR DESCRIPTION
**Pull request by RaphaelNeumann**
A small change that allows operation even in older versions, instantiating the class before calling the method of the same.

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to `master`, could you please submit this to the branch `2.0.x`?

**Comment by sergeyklay** [comment]
@RaphaelNeumann

**Comment by RaphaelNeumann** [comment]
Ok! I do this (https://github.com/phalcon/phalcon-devtools/pull/443) and now i see other lines need fix i will send other pull request soon :) hahahaha

**Comment by sergeyklay** [comment]
I close this in accordance with #443

**Pull request closed without merging**
