### PR TITLE
add option module

### PR DESCRIPTION
**Pull request by seiven**
create controller and model add option module

### CODE REVIEW

**Comment by sergeyklay** [comment]
1. We don't add changes directly to `master` branch. Can you please do PR to `2.0.x` branch? 

2. Can you please fix indents? We use 4 spaces instead of tabs. And indents like:
selection_019

3. Please explain a bit more what exactly fixed/improved/introduced your PR

4. Why did you add int README

> What's we modify?

**Comment by sergeyklay** [comment]
@seiven

**Comment by seiven** [comment]
hi , 
sorry , i'm come form china,so en not good~
push this code to 2.0.x branh?
how to do it? pull 2.0.x code and over it?

**Comment by sergeyklay** [comment]
Yes please

**Comment by seiven** [comment]
thk
ok, plz give me some time. i well do it

**Comment by seiven** [comment]
are you check my code . this Features is useful?

**Pull request closed without merging**
