### PR TITLE
Fix migration Issues

### PR DESCRIPTION
**Pull request by lenrsmith**
I ran into a number of issues with the migration functionality, today. The system was unable to find my migration folders and handle the properly when using time based migrations.

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.0.x` branch?

**Comment by lenrsmith** [comment]
Gladly. Might help to have a note in the contributing instructions. My apologies.

**Comment by sergeyklay** [comment]
Ya, this note already in `3.0.x` :)

**Comment by lenrsmith** [comment]
Awesome, I also noted a few other bugs that I found were fixed. Perfect.

**Pull request closed without merging**
