### PR TITLE
Full migrations log

### PR DESCRIPTION
**Pull request by rusAnthrax**
Now the full log of completed migrations is kept.
During migration/revert process we also look up some missed migrations which may have been created by other developers.
By default migrations log is kept in the `.phalcon/migration-version` file. This behavior may be overridden with `migrationsLog` config parameter or `--migrations-log` command-line parameter.
Database table `phalcon_migrations` is created automatically.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please rebase onto `2.1.x`?

**Comment by rusAnthrax** [comment]
done

**Comment by rusAnthrax** [comment]
more done

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
