### PR TITLE
Rename migrations

### PR DESCRIPTION
**Pull request by zinovyev**
Two specific flags added:

- --ts-base (timestap based) for "migration run" action
- --descr (description) for "migration generate" action.

The migrations folder will be called named the timestamp based mode  _1455789042106821_new_name_, where "1455789042106821" is the current timestamp (in microseconds) and "new_name" is the value of the --descr option.
When you're working in team on a big project, it is a convinient way to name migrations after current timestamp value, thus your migrations wouldn't be overriden.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please submit just the commits that belong to the PR?

**Comment by sergeyklay** [comment]
I think 2.1.x branch is best  place  for this PR

**Comment by zinovyev** [comment]
Ok. I'll fix it to be able to commit changes to the 2.1.x branch. Thanx for this suggestion.

**Comment by zinovyev** [comment]
Moved to https://github.com/phalcon/phalcon-devtools/pull/611

**Pull request closed without merging**
