### PR TITLE
using defined const for Column:TYPE_TIMESTAMP

### PR DESCRIPTION
**Pull request by mattvb91**

### CODE REVIEW

**Comment by sergeyklay** [comment]
I left this here because older versions may not have this constant

**Comment by mattvb91** [comment]
@sergeyklay do we need a 2.1.x branch for changes like this instead?

**Comment by sergeyklay** [comment]
@mattvb91 Can you please send PR to the `2.1.x` branch?

**Comment by mattvb91** [comment]
Thanks @sergeyklay have opened new PR

**Pull request closed without merging**
