### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by dschissler**
When I have time I will move the `APP_PATH` and `BASE_PATH` defines into `index.php` and `launch` for the cli script.  Then I will make it the responsibility of anything that calls into `config.php` to first set these values up.  So for now I'm just expanding on this old work around and when I have time I will improve the design.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Thanks

**Comment by dschissler** [comment]
@sergeyklay There is likely an issue with the Volt setup on at least the `modules` project.  I'm fixing that now.

**Comment by sergeyklay** [comment]
What about https://github.com/phalcon/phalcon-devtools/issues/728

**Comment by dschissler** [comment]
I think that this probably fixes that although he was likely referring to a much older branch.  Please test it a little if you have time because I am busy now with other related activities.

**Comment by dschissler** [comment]
The devtools sometimes refers to to a CDN for jquery and other times the local resources.  This should eventually be resolved and the project should use a constant for jquery versions as well.  I won't be doing that work for a while so maybe for Phalcon 3.1.

**Pull request merged**
