### PR TITLE
Fix Scaffold errors with Phalcon V4

### PR DESCRIPTION
**Pull request by jenovateurs**
Hello team!
I fixed some errors with Scaffold - Phalcon V4.
The way of using Paginator has change.
Paginator return data into an array.
So I updated the correct files.
I also display flash message - a message appears when the search find no result.

Thanks for your review.
* Type: bug fix
* Link to issue: #1429

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines][:contrib:]
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR

Thanks

[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by jenovateurs** [comment]
How can I launch the Codacy/PR Quality Review ?

**Comment by Jeckerson** [comment]
Ignore `Codacy/PR Quality Review`. All another checks are inside Travis CI

**Comment by jenovateurs** [comment]
Thanks @Jeckerson

**Comment by Jeckerson** [comment]
Also don't know, sometimes it just fails...

**Pull request merged**
