### PR TITLE
Add module-directories and namespace-alias parameters

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature
* Link to issue:

This pull request affects the following components: **(please check boxes)**

- [x] Core
- [ ] WebTools
- [ ] Migrations
- [ ] Models
- [x] Scaffold
- [ ] Documentation
- [ ] IDE
- [ ] MySQL
- [ ] PostgreSQL
- [ ] Oracle
- [ ] SQLite
- [ ] Testing
- [ ] Code Quality
- [x] Templating

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines][:contrib:]?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: This PR is adding two things - one is way to tell which directories we want to create when creating module, providing them by comma seperated string. Other thing is `namespace-alias` for model namespace aliases, in my application i have template like:

```php
<?php

namespace @@FQMN@@;

use Phalcon\Config\Adapter\Ini;
use Phalcon\Di;
use Phalcon\DiInterface;
use Phalcon\Loader;
use Phalcon\Mvc\Model\Manager;
use Phalcon\Mvc\ModuleDefinitionInterface;

/**
 * Class Module
 *
 * @package @@FQMN@@
 */
class Module implements ModuleDefinitionInterface
{
    /**
     * Register namespace aliases for PHQL
     */
    public static function registerNamespaceAlias()
    {
        /** @var Manager $modelsManager */
        $modelsManager = Di::getDefault()->getShared('modelsManager');
        $modelsManager->registerNamespaceAlias('@@MNA@@', '@@FQMN@@\Model');
    }
```

This registerNamespaceAlias is called on boostraping of application. This way i can set my model namespace alias when creating module from cli.

Thanks

[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by sergeyklay** [comment]
@Jurigag Could you adapt web tools also? (not just cli)

**Comment by Jurigag** [comment]
Oh okay, will check it out.

**Comment by sergeyklay** [comment]
@Jurigag Could you please submit this PS to the 3.2.x branch

**Comment by sergeyklay** [comment]
@Jurigag ping

**Comment by Jurigag** [comment]
Will try to do this next week, just ping me again next week best so I do
not forget.

02.07.2017 3:38 PM "Serghei Iakovlev" <notifications@github.com> napisał(a):

**Comment by sergeysviridenko** [comment]
@Jurigag Could you please submit this PR to 3.2.x branch?

**Comment by Jurigag** [comment]
@sergeysviridenko yea will need to rebase anyway beacause as i see many changes was since this pr, let me close this for now and i will send it to 3.2.x in future.

**Pull request closed without merging**
