### PR TITLE
Add new type Postgres: Json, Jsonb

### PR DESCRIPTION
**Pull request by whdigger**

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by sergeyklay** [comment]
@whdigger Can you please add check for Phalcon version? 
Json, Jsonb introduced in Phalcon 2.0.4

Also please fix indentation 
selection_039

**Comment by whdigger** [comment]
Fix, What is used in auto-format spaces or tabs?

**Comment by sergeyklay** [comment]
@whdigger For code (non ide stubs) devtools uses 4-spaces for indents. Ide stubs are generated and uses another indent style.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
