### PR TITLE
Added skip/reset auto increment command

### PR DESCRIPTION
**Pull request by 7thcubic**
Fixed branch and command

### CODE REVIEW

**Comment by rianorie** [comment]
nice! Can I be a pain though and ask you to make it --no-auto-increment? While I get what you're doing I think in these cases verbosity is desirable.

**Comment by 7thcubic** [comment]
eh --no-auto-increment isnt that a little long? =d

**Comment by 7thcubic** [comment]
but yeah i could

**Comment by 7thcubic** [comment]
rebase and fixed

**Comment by sergeyklay** [comment]
Can u fix indents please?

**Comment by 7thcubic** [comment]
fixed.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
